#!/bin/bash

# Arturo Borrero <aborrero@cica.es>
#
# Copyright (c) 2013 Arturo Borrero
# This file is released under the GPLv3 license.
#
# Can obtain a complete copy of the license at: http://www.gnu.org/licenses/gpl-3.0.html
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

################################################################
################################################################
# Variables
PID=$$
THIS="`uname -n`"

IPSET="/usr/sbin/ipset"
IPT="/sbin/iptables"
IP4T=$IPT
IP6T="/sbin/ip6tables"
IPT_SAVE="/sbin/iptables-save"
IPT_RESTORE="/sbin/iptables-restore"
IP6T_SAVE="/sbin/ip6tables-save"
IP6T_RESTORE="/sbin/ip6tables-restore"
DIG="/usr/bin/dig"

AUX_FILE="`mktemp`"

LOGGER_BIN="/usr/bin/logger"
ARGS_LOGGER="-t fw-admin[$PID] --"

# For stats
LSMOD="/sbin/lsmod"
FREE="/usr/bin/free"
GETCONF="/usr/bin/getconf"
# Files
VMALLOCINFO="/proc/vmallocinfo"
SLABINFO="/proc/slabinfo"
CONNTRACK_MAX="/proc/sys/net/nf_conntrack_max"
CONNTRACK_COUNT="/proc/sys/net/netfilter/nf_conntrack_count"
CONNTRACK_HASHSIZE="/sys/module/nf_conntrack/parameters/hashsize"


DIR_LIB="/usr/lib/fw-admin.d"
LIB_CONTROL="libfw-admin-control"
LIB_DF="libfw-admin-datafiles"
LIB_UTILS="libfw-admin-utils"
LIB_CHECK="libfw-admin-check"
LIB_OPER="libfw-admin-operations"

. $DIR_LIB/$LIB_CONTROL || { echo "E: Unable to load ${DIR_LIB}/${LIB_CONTROL}" >&2 ; exit 1 ; }
. $DIR_LIB/$LIB_DF || { echo "E: Unable to load ${DIR_LIB}/${LIB_DF}" >&2 ; exit 1 ; }
. $DIR_LIB/$LIB_UTILS || { echo "E: Unable to load ${DIR_LIB}/${LIB_UTILS}" >&2 ; exit 1 ; }
. $DIR_LIB/$LIB_CHECK || { echo "E: Unable to load ${DIR_LIB}/${LIB_CHECK}" >&2 ; exit 1 ; }
. $DIR_LIB/$LIB_OPER || { echo "E: Unable to load ${DIR_LIB}/${LIB_OPER}" >&2 ; exit 1 ; }
