#!/bin/bash
cp ../usr/sbin/fw-admin /usr/sbin/fw-admin
cp ../usr/lib/libfw-admin /usr/lib/libfw-admin
cp ../etc/fw-admin.conf /etc/fw-admin.conf
[ ! -d /var/local/fw.d/data ] && mkdir -p /var/local/fw.d/data
[ ! -d /var/local/fw.d/rules ] && mkdir -p /var/local/fw.d/rules
[ ! -d /var/local/fw.d/run ] && mkdir -p /var/local/fw.d/run
cp data/* /var/local/fw.d/data/
cp rules/* /var/local/fw.d/rules/
#touch /var/local/fw.d/rules/sets ; chmod a+x /var/local/fw.d/rules/sets
