#!/bin/bash
cp ../usr/sbin/fw-admin /usr/sbin/fw-admin
cp ../usr/lib/libfw-admin /usr/lib/libfw-admin
mkdir -p /etc/fw-admin.d/rules
cp ../etc/fw-admin.d/fw-admin.conf /etc/fw-admin.d/fw-admin.conf
[ ! -d /var/lib/fw-admin ] && mkdir -p /var/lib/fw-admin
cp data/* /var/lib/fw-admin/
cp rules/* /etc/fw-admin.d/rules/
