#!/bin/bash

if [ `id -u` -ne 0 ]
then
	echo "W: Not Root!"
	exit 0
fi

#Ejecutable a sbin
cp ../usr/sbin/fw-admin /usr/sbin/fw-admin

#Carpeta librerias
cp -R ../usr/lib/fw-admin.d /usr/lib/

#Carpeta reglas
mkdir /etc/fw-admin.d
cp -R rules /etc/fw-admin.d/

#Fichero config
cp ../etc/fw-admin.d/fw-admin.conf /etc/fw-admin.d/fw-admin.conf

#Carpeta datafiles
[ ! -d /var/lib/fw-admin ] && mkdir -p /var/lib/fw-admin
cp data/* /var/lib/fw-admin/

