Document: fw-admin
Title: Debian fw-admin Manual
Author: <insert document author here>
Abstract: This manual describes what fw-admin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fw-admin/fw-admin.sgml.gz

Format: postscript
Files: /usr/share/doc/fw-admin/fw-admin.ps.gz

Format: text
Files: /usr/share/doc/fw-admin/fw-admin.text.gz

Format: HTML
Index: /usr/share/doc/fw-admin/html/index.html
Files: /usr/share/doc/fw-admin/html/*.html
