#!/bin/bash

set -e

# Add service
update-rc.d fw defaults >/dev/null

if [ "$1" == "configure" ] && [ -z "$2" ]
then
	# Do a basic installation of datafiles
	fw-admin --check-datafiles --install

	# Only start service if is a new installation, no update.
	invoke-rc.d fw start
fi


exit 0
