#!/bin/bash

# Example rules for vlan_1

$IPT -A vlan_1 -m set --match-set $REPOS dst -p tcp --dport 443 -j ACCEPT

$IPT -A vlan_1 -s $NET_VLAN1 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN2 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN4 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN6 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN7 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN8 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN10 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN11 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN12 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN18 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN19 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN23 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN27 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
