#!/bin/bash

# Example rules for vlan_1

$IPT -A vlan_1 -m set --match-set $REPOS dst -p tcp --dport 443 -j ACCEPT

$IPT -A vlan_1 -s $NET_VLAN1 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN2 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN4 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN6 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN7 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN8 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN10 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN11 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN12 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN18 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN19 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN23 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT
$IPT -A vlan_1 -s $NET_VLAN27 -m set --match-set $REPOS dst -p tcp --dport 80 -m state --state NEW -j ACCEPT

# VOID issues test
$IPT -A vlan_1 -s $WWW_GOOGLE_COM -m state --state NEW -m comment --comment "void1" -j ACCEPT
$IPT -A vlan_1 -s $WWW_GOOGLE_COM -d $V192_168_0_1 -m state --state NEW -m comment --comment "void2" -j ACCEPT
$IPT -A vlan_1 -s $V2A00_9AC0_C1CA__1 -d $V192_168_0_1 -m state --state NEW -m comment --comment "void3" -j ACCEPT
$IPT -A vlan_1 -s $V2A00_9AC0_C1CA__1 -m state --state NEW -m comment --comment "void4" -j ACCEPT
$IPT -A vlan_1 -s $VOID -m comment --comment "void5" -j ACCEPT

