#!/bin/bash

# Arturo Borrero <aborrero@cica.es> Marzo/Abril/Mayo/Junio/Julio 2012

CONF_FILE="/etc/fw-admin.conf"
LIB="/usr/lib/libfw-admin"

C_RED="\E[31m"
C_GREEN="\E[32m"
C_YELLOW="\E[33m"
C_BLUE="\E[34m"
C_REDBOLD="\E[1;31m"
C_GREENBOLD="\E[1;32m"
C_YELLOWBOLD="\E[1;33m"
C_BLUEBOLD="\E[1;33m"
C_NORMAL="\E[0m"
C_BOLD="\E[1m"

ayuda()
{
	echo -e "${C_BOLD}fw-admin Version: $VERSION${C_NORMAL}"
	uso
	echo -e "	${C_BOLD}-s${C_NORMAL}				Muestra estadisticas."
	echo -e "	${C_BOLD}-a${C_NORMAL} [ipv4|ipv6|fqdn]		Agregar una variable al sistema, ya sea IP o FQDN."
	echo -e "	${C_BOLD}-as${C_NORMAL} [nombreset]			Agregar una variable de nombre de conjunto al sistema."
	echo -e "	${C_BOLD}-r${C_NORMAL}				Recarga el valor de todas las variables guardadas."
	echo -e "	${C_BOLD}-i${C_NORMAL} [ipv4|ipv6|fqdn|var]		Obtener informacion de una IP, FQDN, variable o set."
	echo -e "	${C_BOLD}-c${C_NORMAL} fichero			Comprueba las variables de un fichero de vlan o set."
	echo -e "	${C_BOLD}--start${C_NORMAL} {vlan|nat|core}		Inicia las reglas de una vlan/nat/core. Esto también sirve como reload."
	echo -e "	${C_BOLD}--stop${C_NORMAL} {vlan|nat|core}		Elimina las reglas de una vlan/nat/core."
	echo -e "	${C_BOLD}--ipset-reload${C_NORMAL}			Recarga los datos de conjuntos de IPs."
	echo -e "	${C_BOLD}--help${C_NORMAL}				Muestra esta ayuda."
	echo -e "Para mas información consultar ${C_BOLD}fw-admin(8)${C_NORMAL}"

	return 0
}

uso()
{
	echo -e "${C_BOLD}Uso:${C_NORMAL} fw-admin {-s|-a [ipv4|ipv6|fqdn]|-as [nombreset]|-r|-i [ipv4|ipv6|fqdn|var]|-c fichero|--start {vlan|nat|core}|--stop {vlan|nat|core}|--ipset-reload|--help}"
	return 0
}


################################################################
################################################################
# Programa
################################################################
################################################################
source $CONF_FILE || { echo "E: Unable to load config file $CONF_FILE" >&2; exit 1 ; }

if [ "$1" == "-s" ] || [ "$1" == "-a" ] || [ "$1" == "-as" ] || [ "$1" == "-r" ] || [ "$1" == "-i" ] || [ "$1" == "-c" ] || [ "$1" == "--start" ] || [ "$1" == "--stop" ] || [ "$1" == "--ipset-reload" ]
then
	source $LIB || { echo "E: Unable to load library $LIB" >&2; exit 1 ; }
	check_root
	check_files || { message "Terminando..." ; exit 1 ; }
fi

case "$1" in

	"-s" )
		message "I: Mostrando estadisticas."
		estadisticas
		do_exit $?
		;;

	"-a" )
		validar_ejecucion
		message "I: Agregando variable de IP o FQDN."
		agregar_variable $2 #dato como parametro
		do_exit $?
		;;
	"-as" )
		validar_ejecucion
		message "I: Agregando variable de conjunto."
		agregar_set $2 #dato como parametro
		do_exit $?
		;;
	"-r" )
		validar_ejecucion
		message "I: Recargando variables."
		recargar_variables
		do_exit $?
		;;
	"-i" )
		message "I: Obteniendo informacion."
		obtener_informacion $2 #dato como parametro
		do_exit $?
		;;
	"-c" )
		checkear_fichero $2 #fichero de vlan como parametro
		do_exit $?
		;;
	"--start" )
		validar_ejecucion
		message "I: Inicializando reglas de iptables [$2]."
		[ "$3" == "--nocheck" ] && flag_no_check=1
		start $2 #nombre de vlan como parametro
		do_exit $?
		;;
	"--stop" )
		validar_ejecucion
		message "I: Parando reglas de iptables de [$2]."
		stop $2 #nombre de vlan como parametro
		do_exit $?
		;;
	"--ipset-reload" )
		validar_ejecucion
		message "I: Recargando conjuntos."
		[ "$2" == "--nocheck" ] && flag_no_check=1
		ipset_reload #sin parametros
		do_exit $?
		;;
	"--help" )
		ayuda
		exit $?
		;;
	* )
		uso
		exit $?
		;;
esac
